### PR TITLE
DerivedFrom trait

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
bors try

**Comment by Disasm** [comment]
Are you sure this should be in svd *parser*?

**Comment by burrbull** [comment]
Not, I'm not sure. But it should not be in `svd2rust` too.

**Comment by Disasm** [comment]
Why do you think so? Are there any other "users" of this high-level functionality?

**Comment by burrbull** [comment]
Rebased on #83

**Comment by burrbull** [comment]
I located all `derive_from()` in separate file under the feature.

It will be easier to move this in `svd2rust` or other crate if we decide.

**Comment by burrbull** [comment]
@therealprof  can we make new release with this PR?

**Comment by therealprof** [comment]
@burrbull Can you remind me what these changes do and how to use them? Especially since they're behind a feature gate that might some some interesting implications.

**Comment by burrbull** [comment]
It is needed to unify copying of 'derived' items (peripherals, registers, fields, etc.).
Now this functionality partially in in `svd-parser` and partially in `svd2rust` (https://github.com/rust-embedded/svd2rust/blob/11e11f0498c0aca1042eb927e2aa74c246a8b4a0/src/generate/peripheral.rs#L100).

Also https://github.com/rust-embedded/svd2rust/pull/372 requires it.
I've moved this under feature because this does not apply directly to parsing.

**Comment by therealprof** [comment]
Okay, but before releasing we should properly modernize this crate, meaning:

1. Bump the dependencies
2. Turn it into edition 2018
3. Update the including the repository URL
4. Touch up the CHANGELOG.md to match the previous versions, bump the version and release it

**Pull request merged**
