### PR TITLE
always trim whitespaces

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
cc @Emilgardis
I see 3 ways to fix #228 :
1. Always allow whitespaces (this PR).
2. Don't allow on `strict`:
2a. Change `ElementExt` to get `Config`. *Breaking change*, require version bump.
2b. Wrappers for `ElementExt` methods and replace them on each usage.

**Comment by thejpster** [comment]
This PR only changes the CHANGELOG and nothing else?

**Comment by burrbull** [comment]
Sorry

**Review by thejpster — APPROVED** [review]
Makes sense to me

**Comment by Emilgardis** [comment]
I'm not sure I like this approach, but there shouldn't realistically be a scenario where a leading/trailing whitespace is meaningful so it's fine

**Comment by burrbull** [comment]
> I'm not sure I like this approach, but there shouldn't realistically be a scenario where a leading/trailing whitespace is meaningful so it's fine

I'm going to change this in future. I just don't want to do major release for such little change.

**Pull request merged**
