### PR TITLE
Fix enumeratedValues parsing

### PR DESCRIPTION
**Pull request by Disasm**
Checks that `enumeratedValues` elements do not contain unexpected tags.
Also checks that `enumeratedValues` contains at least one `enumeratedValue`.

### CODE REVIEW

**Comment by Disasm** [comment]
Fixed the warnings. I'm not sure if `// TODO: is this correct? probably not, need tests` comment is obsolete, maybe @ryankurte could say something.

**Comment by Disasm** [comment]
bors try

**Comment by Emilgardis** [comment]
bors try

**Comment by Disasm** [comment]
Fixed.

**Comment by Emilgardis** [comment]
bors try

**Comment by burrbull** [comment]
It would be good also to check if <enumeratedValues> contains items with identical names or values.

**Comment by Disasm** [comment]
@burrbull, agree, but this semantic information check matches `svd2rust` better. Added an issue for this.

**Comment by burrbull** [comment]
@Disasm can you resolve conflicts?

**Comment by Disasm** [comment]
Done!
I excluded fix of these lines: https://github.com/rust-embedded/svd/blob/d7464ff910afa321717b1a97bf46afc13a6148a0/src/svd/register.rs#L65-L68
Maybe it's better to add it with a separate change.

**Comment by burrbull** [comment]
bors try

**Pull request merged**
