### PR TITLE
Fix clippy for MSRV 1.36

### PR DESCRIPTION
**Pull request by brainstorm**
Fixes https://github.com/rust-embedded/svd/issues/135

### CODE REVIEW

**Comment by MarcoIeni** [comment]
Can you remove comments and todo [here](https://github.com/rust-embedded/svd/blob/master/.github/workflows/clippy.yml) ?

**Comment by MarcoIeni** [comment]
> Kind of wish that formatting was automatically run on CI

mmm never seen this in any other rust project, I don't really like the idea that CI changes your code.

**Comment by MarcoIeni** [comment]
You can allow individual clippy warnings in some parts of the code if you don't want to introduce breaking changes or stuff like that.
See [this](https://github.com/dandavison/delta/commit/15d06cbf7584570ec3b5beaba99cb8898f9ec3dc) example

**Review by Emilgardis — CHANGES_REQUESTED** [review]
Nice!

Adress remaining clippy warns except allow the one on `is_default`

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
@Emilgardis

**Comment by MarcoIeni** [comment]
looks good to me

**Review by Emilgardis — APPROVED** [review]
bors r+

**Comment by Emilgardis** [comment]
bors ping

bors r+

**Pull request merged**
