### PR TITLE
Add README.md to Cargo.toml

### PR DESCRIPTION
**Pull request by therealprof**
Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by burrbull** [comment]
I did not make `derive_from` mod public :cry:

**Comment by therealprof** [comment]
bors r=burrbull

**Comment by burrbull** [comment]
@therealprof What is the best way to deal with absent `pub`? Make new release?

**Comment by therealprof** [comment]
Yes.

**Pull request merged**
