### PR TITLE
encode dimIndex ranges

### PR DESCRIPTION
**Pull request by burrbull**
cc @adamgreig 
Partially related to https://github.com/stm32-rs/stm32-rs/pull/701#issuecomment-1036982033

### CODE REVIEW

**Comment by burrbull** [comment]
cc @Emilgardis

**Review by adamgreig — APPROVED** [review]
LGTM. Maybe worth fixing the clippy lint about the `return Some(min..=max);`?

I also think the `max.wrapping_sub(min)` could just be `(max - min)` since it can't ever underflow, but it doesn't really matter here.

bors d+

**Review by adamgreig — APPROVED** [review]
hah, what use is bors delegating if as soon as you push a commit it revokes approval?

bors r+

**Comment by therealprof** [comment]
> hah, what use is bors delegating if as soon as you push a commit it revokes approval?
> 
> bors r+

Yeah, need to change the configuration to not dismiss a review after a new commit.

**Comment by Emilgardis** [comment]
> > hah, what use is bors delegating if as soon as you push a commit it revokes approval?
> > bors r+
> 
> Yeah, need to change the configuration to not dismiss a review after a new commit.

it's quite easy to change branch protection rules, should we?

image

**Comment by therealprof** [comment]
I'm all for it, especially for projects with little risk of abuse (like sneaking in changes after approval of unmergeable PRs). However we'd have to be more permissive in our rules: https://github.com/rust-embedded/wg/blob/master/ops/post-transfer.md#repository-settings

**Pull request merged**
