### PR TITLE
move all check_name's under strict feature

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by adamgreig** [comment]
bors try

**Comment by adamgreig** [comment]
Looks like clippy is failing with:

error: error reading Clippy's configuration file `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.40/.clippy.toml`: unknown field `msrv`, expected one of `blacklisted-names`, `cognitive-complexity-threshold`, `cyclomatic-complexity-threshold`, `doc-valid-idents`, `too-many-arguments-threshold`, `type-complexity-threshold`, `single-char-binding-names-threshold`, `too-large-for-stack`, `enum-variant-name-threshold`, `enum-variant-size-threshold`, `verbose-bit-mask-threshold`, `literal-representation-threshold`, `trivial-copy-size-limit`, `too-many-lines-threshold`, `third-party`

I think we need to include the bump in Rust version clippy uses from #140 (https://github.com/rust-embedded/svd/pull/140/files#diff-8fbf9e9b0b12515f84b26e686fd2e8fa9877b4a11348bcfddff2f4e33007f977R15) to this PR before we can merge this one. @therealprof I guess this is also a reason to bump the MSRV!

**Review by adamgreig — APPROVED** [review]

**Comment by adamgreig** [comment]
This PR can merge as part of #140.

**Comment by therealprof** [comment]
@adamgreig Well, well... 😉

**Pull request closed without merging**
