### PR TITLE
v0.10.0

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by adamgreig** [comment]
Do you think this is ready for 1.0 instead of 0.10? I don't really have a handle on it...

**Comment by burrbull** [comment]
> Do you think this is ready for 1.0 instead of 0.10? I don't really have a handle on it...

You're right. I'll change it to 0.10.

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

bors r+

Are you going to do the release or do you want me to?

**Comment by burrbull** [comment]
> Are you going to do the release or do you want me to?

I can miss something, so please do it.

**Pull request merged**
