### PR TITLE
v0.8.0

### PR DESCRIPTION
**Pull request by burrbull**
>Okay, but before releasing we should properly modernize this crate, meaning:
>
>    1. Bump the dependencies
>    2. Turn it into edition 2018
>    3. Update the including the repository URL
>    4. Touch up the CHANGELOG.md to match the previous versions, bump the version and release it

All dependencies are actual and edition2018 is on.
~Don't know what you mean in item `#3`.~

### CODE REVIEW

**Comment by burrbull** [comment]
cc @therealprof

**Comment by burrbull** [comment]
Done.

**Comment by therealprof** [comment]
Would you mind adding a maintanance note to README.md?

> This project is developed and maintained by the Tools team.

Also ToolsTeam in Cargo.toml reads a bit weird. I understand that's what we did for `svd2rust` but maybe we can have a blank between Tools and Team here. ;)

**Comment by burrbull** [comment]
Is this better?

**Pull request merged**
