### PR TITLE
cleanup install.sh & bump dependencies

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
bors try

**Comment by burrbull** [comment]
`bors` don't work now

**Comment by burrbull** [comment]
And I have green `Merge pull request` without review. Is this normal?
cc @japaric 
cc @therealprof

**Comment by therealprof** [comment]
@burrbull That needs to be set up first. I noticed just now that the repo has been moved.

**Comment by burrbull** [comment]
> @burrbull That needs to be set up first. I noticed just now that the repo has been moved.

I get 404 when try to enter bors-ng as rust-embedded.

**Comment by therealprof** [comment]
bors ping

**Comment by therealprof** [comment]
@burrbull Try now.

**Comment by burrbull** [comment]
bors try

**Comment by therealprof** [comment]
Branch protection is also on now.

**Comment by burrbull** [comment]
@therealprof can you add review now?

**Pull request merged**
