### PR TITLE
v0.13

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by thejpster** [comment]
Hmm. Looks OK, but I think I'd prefer to see the new example and the serialisation changes in a separate PR.

**Comment by burrbull** [comment]
> Hmm. Looks OK, but I think I'd prefer to see the new example and the serialisation changes in a separate PR.

#188

**Comment by burrbull** [comment]
cc @rust-embedded/tools

**Review by thejpster — APPROVED** [review]

**Comment by burrbull** [comment]
Need to merge #192 first

**Review by adamgreig — APPROVED** [review]
LGTM. I noticed we don't have links in the changelog any more, but still use the `[v0.13.0]` style headers. Maybe worth adding links? They would have to be to the whole-repository but I guess it's OK.

**Comment by burrbull** [comment]
> LGTM. I noticed we don't have links in the changelog any more, but still use the `[v0.13.0]` style headers. Maybe worth adding links? They would have to be to the whole-repository but I guess it's OK.

Ok. I'll try to do this

**Review by adamgreig — APPROVED** [review]
Thanks!

bors merge

**Pull request merged**
