### PR TITLE
Write Builders manually

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by Emilgardis** [comment]
A lot of noise from cargo fmt (I assume). Could you split it up?

**Comment by therealprof** [comment]
I don't think the rustfmt noise is too present. Do you mean we should rustfmt before this PR?

**Comment by Emilgardis** [comment]
No, I mean one commit for rustfmt and one with the builder changes.

**Comment by burrbull** [comment]
I am not able to split them.

**Comment by therealprof** [comment]
> No, I mean one commit for rustfmt and one with the builder changes.

Same thing. ;)

**Comment by burrbull** [comment]
cc @WRansohoff
with last commit serde serialization must be much cleaner
Test, please.

**Comment by therealprof** [comment]
Looks good to me. But it would be nice to read a few words about the motivation and consequences of this change.

**Comment by burrbull** [comment]
The motivation is simple: `serde` trash cleaning.
With `b44d3c3` you serialize/deserialize only significant fields of structures without `None` or empty or `_extensible`.

**Comment by burrbull** [comment]
```json
  "peripherals": [
    {
      "_extensible": null,
      "address_block": {
        "offset": 0,
        "size": 12,
        "usage": "registers"
      },
      "base_address": 1073741824,
      "default_register_properties": {
        "_extensible": null,
        "access": null,
        "reset_mask": null,
        "reset_value": null,
        "size": null
      },
      "derived_from": null,
      "description": "Flash Memory",
      "display_name": null,
      "group_name": "FLASH_IF",
      "interrupt": [],
      "name": "FLASH_IF",
      "registers": [
        {
          "Register": {
            "Single": {
              "_extensible": null,
              "access": "ReadWrite",
              "address_offset": 0,
              "alternate_group": null,
              "alternate_register": null,
              "derived_from": null,
              "description": "Flash Access Size Register",
              "fields": [
                {
                  "Single": {
                    "_extensible": null,
                    "access": "ReadWrite",
                    "bit_range": {
                      "offset": 0,
                      "range_type": "MsbLsb",
                      "width": 2
                    },
                    "derived_from": null,
                    "description": "Flash Access Size ",
                    "enumerated_values": [],
                    "modified_write_values": null,
                    "name": "ASZ",
                    "write_constraint": null
                  }
                }
              ],
              "modified_write_values": null,
              "name": "FASZR",
              "reset_mask": 3,
              "reset_value": 2,
              "size": 32,
              "write_constraint": null
            }
          }
        },
```
compare with:
```json
  "peripherals": [
    {
      "address_block": {
        "offset": 0,
        "size": 12,
        "usage": "registers"
      },
      "base_address": 1073741824,
      "default_register_properties": {},
      "description": "Flash Memory",
      "group_name": "FLASH_IF",
      "name": "FLASH_IF",
      "registers": [
        {
          "Register": {
            "Single": {
              "access": "ReadWrite",
              "address_offset": 0,
              "description": "Flash Access Size Register",
              "fields": [
                {
                  "Single": {
                    "access": "ReadWrite",
                    "bit_range": {
                      "offset": 0,
                      "range_type": "MsbLsb",
                      "width": 2
                    },
                    "description": "Flash Access Size ",
                    "name": "ASZ"
                  }
                }
              ],
              "name": "FASZR",
              "reset_mask": 3,
              "reset_value": 2,
              "size": 32
            }
          }
        },
```

**Comment by cr1901** [comment]
@Emilgardis What is the status of this PR? I'm [trying](https://github.com/rust-embedded/svd/issues/111#issuecomment-616257210) to remove an outdated in-tree version of `svd_parser` in [`msp430_svd`](https://github.com/pftbest/msp430_svd). I need either this or a default implementation of `Peripherals` struct so I can create my own; the `_extensible` field forbids me from creating my own.

**Comment by burrbull** [comment]
Closed. See #115

**Pull request closed without merging**
