### PR TITLE
rename RegisterClusterArrayInfo -> DimElement

### PR DESCRIPTION
**Pull request by burrbull**
https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_special.html#dimElementGroup_gr

### CODE REVIEW

**Comment by burrbull** [comment]
bors try

**Comment by therealprof** [comment]
Please try to stick to one change per PR instead of building on other PRs.

**Comment by therealprof** [comment]
I'll have a look once the clippy PR is in which hopefully cancels out the noise.

**Comment by burrbull** [comment]
Rebased on master.

**Comment by therealprof** [comment]
LGTM

**Pull request merged**
